# Generated by Django 5.1.6 on 2025-02-11 02:43

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="custom_folder",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(upload_to=myapp.models.user_directory_path),
        ),
    ]
